apiVersion: v1
kind: Service
metadata:
  name: healthcare-service
spec:
  selector:
    app: healthapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30036
  type: NodePort
